version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      cargo-weekly:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      ci-weekly:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-weekly:
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: /npm/git-cliff
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      npm-weekly:
        patterns:
          - '*'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: UTC
    open-pull-requests-limit: 10
    groups:
      docker-weekly:
        patterns:
          - '*'
